network:
  version: 1
  config:
  - type: physical
%{ if image == "ubuntu2004o" || image == "ubuntu1804o" || image == "ubuntu1604o" }
    name: ens3
%{ else }
    name: eth0
%{ endif }
    subnets:
      - type: dhcp
