#!/bin/bash
# combustion: network prepare
set -euxo pipefail

function nm_config() {
  connectiondir="/etc/NetworkManager/system-connections"
  connectionfile="$connectiondir/Wired connection $1.nmconnection"
  mkdir -p "$connectiondir"
  cat > "$connectionfile" <<EOF
[connection]
id=Wired connection $1
type=ethernet
interface-name=$2

[ipv4]
method=$3

[ipv6]
addr-gen-mode=eui64
method=auto
EOF
  chmod go-r "$connectionfile"
}

# Name the Network Manager connections (preparation phase in initrd)
if [ "$${1-}" = "--prepare" ]; then
  nm_config 1 eth0 auto
  nm_config 2 eth1 manual
  exit 0
fi

# Redirect output to the console
exec > >(exec tee -a /var/log/combustion) 2>&1

# Name the Network Manager connections (final phase on real filesystem)
nm_config 1 eth0 auto
nm_config 2 eth1 manual

# Set linux as password for root
echo 'root:$6$3aQC9rrDLHiTf1yR$NoKe9tko0kFIpu0rQ2y/OzOOtbVvs0Amr2bx0T4cGf6aq8PG74EmVy8lSDJdbLVVFpOSzwELWyReRCiPHa7DG0' | chpasswd -e

# 5.1 --> SL micro 6.1
%{ if product_version == "5.1-paygo" }
echo "PermitRootLogin yes" > /etc/ssh/sshd_config.d/root.conf
echo "ChallengeResponseAuthentication yes" >> /etc/ssh/sshd_config.d/root.conf
%{ else }
# 5.0 --> SLE Micro 5.5
echo "PermitRootLogin yes" > /etc/ssh/sshd_config
echo "ChallengeResponseAuthentication yes" >> /etc/ssh/sshd_config
echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
%{ endif }

# Add a public ssh key and enable sshd
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGEPA8UvZ/6tTiL+MKGUAsHJuPlDpueeDmbuJ+0giOCY root@controller" > /root/.ssh/authorized_keys

systemctl enable sshd.service
systemctl restart sshd.service

# Install packages
PACKAGES=""

%{ if install_salt_bundle }
PACKAGES="$PACKAGES venv-salt-minion"
%{ else }
PACKAGES="$PACKAGES salt-minion"
%{ endif }

transactional-update --non-interactive --continue pkg in $PACKAGES

# Leave a marker
echo "Configured with combustion" > /var/lib/combustion.done

reboot
