#! /bin/bash
set -xe

cat >grains <<EOF
init: systemd
hostname: suma-refhead-cli
gpg_keys: []
domain: travis
use_avahi: 0
timezone: Europe/Berlin
use_ntp: true
additional_repos: {}
additional_certs: {}
additional_packages: []
authorized_keys: [ssh-rsa 1233= root@travis.git]
reset_ids: true
product_version: head
server: travis.tf.local
roles: [client]
mirror: null
auto_register: false
testsuite: true
ipv6: {'accept_ra': true, 'enable': true}
EOF

cat >minion <<EOF
root_dir: $PWD
id: travis-client-validation
EOF

salt-call state.show_highstate --local --file-root=salt/ --config-dir=. --retcode-passthrough
