#! /bin/bash
set -xe

cat >grains <<EOF
init: systemd
hostname: suma-refhead-cli
gpg_keys: []
domain: travis
use_avahi: 0
timezone: Europe/Berlin
additional_repos: {}
additional_packages: []
authorized_keys: [ssh-rsa 1233= root@travis.git]
reset_ids: true
product_version: head
server: travis.tf.local
proxy: null
client: cli-travis.tf.local
minion: min-travis.tf.local
centos_minion: 100-travis.tf.local
ssh_minion: ssh-travis.tf.local
roles: [controller]
mirror: null
testsuite: true
EOF

cat >minion <<EOF
root_dir: $PWD
id: travis-ctl-validation
EOF

salt-call state.show_highstate --local --file-root=salt/ --config-dir=. --retcode-passthrough
