#! /bin/bash
set -xe

cat >grains <<EOF
init: systemd
hostname: suma-refhead-srv
gpg_keys: []
domain: travis
use_avahi: 0
timezone: Europe/Berlin
additional_repos: {}
additional_packages: []
authorized_keys: [ssh-rsa 1233= root@travis.git]
reset_ids: true
version: head
cc_username: UC7
cc_password: passme
mirror: null
iss_master: null
iss_slave: null
smt: null
role: suse_manager_server
for_development_only: 0
disable_firewall: 0
allow_postgres_connections: 0
testsuite: true
unsafe_postgres: 1
use_unreleased_updates: 0
monitored: 0
log_server: null
from_email: null
traceback_email: null
EOF

cat >minion <<EOF
root_dir: $PWD
id: travis
EOF

salt-call state.show_highstate --local --file-root=salt/ --config-dir=. --retcode-passthrough
