#! /bin/bash
set -xe

# complete missing passwords in example files
sed -i 's/\.\.\./"not used"/g' *.example
sed -i '/provider *"/,/\}/d' *.example

ln -sfn ../backend_modules/null modules/backend

# validate examples
for tf_file in `ls main.tf.*.example`; do
  echo "Validating $tf_file..."
  cp $tf_file main.tf
  # uncomment for Terraform detailed logging
  # export TF_LOG=TRACE
  terraform init
  terraform validate
  terraform apply -auto-approve
  terraform destroy -auto-approve
  echo
done
