#cloud-config

yum_repos:
  # repo for salt
  # use `next` development repo while EL10 client tools channel doesn't exist
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/saltstack:/bundle:/next:/AlmaLinux10/AlmaLinux_10/
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/10/Everything/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-10&arch=$basearch
    enabled: true
    gpgcheck: false
    name: epel

runcmd:
  # WORKAROUND: cloud-init in Alma 10 does not take care of the following
  # TBD: check if needed as it's just copy from Alma 9 section
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - "dnf -y install venv-salt-minion avahi nss-mdns qemu-guest-agent dbus-tools"

