#cloud-config

bootcmd:
  # WORKAROUND: yum_repos state cant replace a repo, so we need to delete it,
  # otherwise the workaround for archived repo doesn't work
  - [rm, -f, /etc/yum.repos.d/CentOS-Base.repo, /etc/yum.repos.d/CentOS-AppStream.repo]

yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8/
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/8/Everything/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch
    enabled: true
    gpgcheck: false
    name: epel
  # repo for Centos-Base backup
  CentOS-Base_backup:
    baseurl: http://vault.centos.org/$contentdir/$releasever/BaseOS/$basearch/os/
    enabled: true
    gpgcheck: false
    name: CentOS-Base_backup
  # repo for Centos-Appstream backup
  CentOS-Appstream_backup:
    baseurl: http://vault.centos.org/$contentdir/$releasever/AppStream/$basearch/os/
    enabled: true
    gpgcheck: false
    name: CentOS-AppStream_backup

runcmd:
%{ if install_salt_bundle ~}
  - "dnf -y install venv-salt-minion avahi nss-mdns qemu-guest-agent"
%{ else ~}
  - "dnf -y install salt-minion avahi nss-mdns qemu-guest-agent"
%{ endif ~}
