#cloud-config

zypper:
  repos:
    - id: tools_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Stable:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/
      enabled: true
      gpgcheck: false
      name: tools_pool_repo

runcmd:
%{ if container_server && testsuite ~}
  # Packages needed for the testsuite
  - "zypper -n in expect"
%{ endif ~}
%{ if install_salt_bundle ~}
  - "zypper -n in venv-salt-minion avahi nss-mdns"
%{ else ~}
  - "zypper -n in avahi nss-mdns"
%{ endif ~}
  - "zypper removerepo --all"
