#cloud-config

yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Stable:/EL8-Uyuni-Client-Tools/EL_8
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/8/Everything/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch
    enabled: true
    gpgcheck: false
    name: epel

runcmd:
%{ if install_salt_bundle ~}
  - "dnf -y install venv-salt-minion avahi nss-mdns qemu-guest-agent"
%{ else ~}
  - "dnf -y install avahi nss-mdns qemu-guest-agent salt-minion"
%{ endif ~}
