#cloud-config

yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Stable:/EL9-Uyuni-Client-Tools/EL_9
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/9/Everything/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=$basearch
    enabled: true
    gpgcheck: false
    name: epel

runcmd:
  # WORKAROUND: cloud-init in Rocky 9 does not take care of the following
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd
%{ if install_salt_bundle ~}
  - "dnf -y install venv-salt-minion avahi nss-mdns dbus-tools"
%{ else ~}
  - "dnf -y install avahi nss-mdns salt-minion dbus-tools"
%{ endif ~}
