#cloud-config

write_files: ${ files ~}

zypper:
  repos:
%{ if container_server ~}
%{ if product_version == "5.0-nightly" ~}
    - id: container_utils_repo
      name: container_utils_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/Devel:/Galaxy:/Manager:/5.0/images/repo/SUSE-Manager-Server-5.0-POOL-x86_64-Media1/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endif ~}
%{ if product_version == "5.0-released" ~}
    - id: container_utils_pool_repo
      name: container_utils_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Products/SUSE-Manager-Server/5.0/x86_64/product
      enabled: 1
      autorefresh: 1
      gpgcheck: false
    - id: container_utils_updates_repo
      name: container_utils_updates_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Updates/SUSE-Manager-Server/5.0/x86_64/update
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endif ~}
%{ endif ~}
%{ if container_proxy ~}
%{ if product_version == "5.0-nightly" ~}
    - id: container_utils_repo
      name: container_utils_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/Devel:/Galaxy:/Manager:/5.0/images/repo/SUSE-Manager-Proxy-5.0-POOL-x86_64-Media1/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endif ~}
%{ if product_version == "5.0-released" ~}
    - id: container_utils_pool_repo
      name: container_utils_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Products/SUSE-Manager-Proxy/5.0/x86_64/product
      enabled: 1
      autorefresh: 1
      gpgcheck: false
    - id: container_utils_updates_repo
      name: container_utils_updates_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Updates/SUSE-Manager-Proxy/5.0/x86_64/update
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endif ~}
%{ endif ~}
%{ if testsuite ~}
    # Required only for wget
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Products/SLE-Module-Basesystem/15-SP5/x86_64/product
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endif ~}
    - id: ca_suse
      name: ca_suse
      baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/SUSE:/CA/SLE_15_SP5/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
    - id: micro_pool_repo
      name: micro_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Products/SLE-Micro/5.5/x86_64/product/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
    - id: micro_update_repo
      name: micro_update_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/SUSE/Updates/SLE-Micro/5.5/x86_64/update/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
    - id: tools_pool_repo
      name: tools_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "dist.suse.de/ibs" }/Devel:/Galaxy:/Manager:/5.0:/SLE15-SUSE-Manager-Tools/images/repo/SLE-15-Manager-Tools-POOL-x86_64-Media1/
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ for name, url in jsondecode(additional_repos) ~}
    - id: ${name}_repo
      name: ${name}_repo
      baseurl: ${url}
      enabled: 1
      autorefresh: 1
      gpgcheck: false
%{ endfor ~}

runcmd:
  - [transactional-update, run, sh, -c, "for key in $(ls /etc/gpg_keys); do rpm --import /etc/gpg_keys/$key; done" ]
  - [ zypper, mr, -a, -g ]
%{ if testsuite ~}
  # Packages needed for the testsuite
  - [ transactional-update, --continue, --non-interactive, pkg, install, wget, timezone, expect, ca-certificates ]
%{ endif ~}
%{ if container_server ~}
  - [ transactional-update, --continue, --non-interactive, pkg, install, mgrctl, mgradm, uyuni-storage-setup-server, netavark, aardvark-dns, ca-certificates-suse ]
%{ endif ~}
%{ if container_proxy ~}
  - [ transactional-update, --continue, --non-interactive, pkg, install, mgrpxy, ca-certificates-suse ]
%{ endif ~}
%{ if install_salt_bundle ~}
  - [ transactional-update, --continue, --non-interactive, pkg, install, qemu-guest-agent, venv-salt-minion, avahi ]
%{ else ~}
  - [ transactional-update, --continue, --non-interactive, pkg, install, qemu-guest-agent, salt-minion, avahi ]
%{ endif ~}
  - [ reboot ]
