#! /bin/bash
set -x

mkdir -p testconfig

cat > testconfig/grains <<EOF
hostname: sumaform-test-server
gpg_keys: []
domain: tf.local
use_avahi: 0
timezone: Europe/Berlin
use_ntp: true
additional_repos: {}
additional_certs: {}
additional_packages: []
authorized_keys: [ssh-rsa 1233= root@sumaform.git]
reset_ids: true
product_version: head
cc_username: github
cc_password: passme
mirror: null
server_mounted_mirror: null
iss_master: null
iss_slave: null
smt: null
roles: [server]
disable_firewall: 0
allow_postgres_connections: 0
unsafe_postgres: 1
java_debugging: 0
skip_changelog_import: 0
create_first_user: 0
mgr_sync_autologin: 0
create_sample_channel: 0
create_sample_activation_key: 0
create_sample_bootstrap_script: 0
publish_private_ssl_key: 0
testsuite: true
monitored: 0
from_email: null
traceback_email: null
ipv6: {'accept_ra': true, 'enable': true}
install_salt_bundle: true
db_configuration: {'local': true, 'hostname': 'localhost', 'port': '5432'}
repository_disk_size: 0
EOF

cat > testconfig/minion <<EOF
root_dir: $PWD
id: sumaform-test-server
EOF

cat testconfig/grains
echo

salt-call state.show_highstate --local --file-root=salt/ --config-dir=testconfig --retcode-passthrough
