#! /bin/bash
set -x

mkdir -p testconfig

cat > testconfig/grains <<EOF
roles: [controller]

# Override OS information for testing
os: 'SUSE'
os_family: 'Suse'
osarch: 'x86_64'
oscodename: 'openSUSE Leap 15.5'
osfinger: 'Leap-15'
osfullname: 'Leap'
osmajorrelease: 15
osrelease: '15.5'
osrelease_info: [15, 5]

# Set grain values in such a way that covers as many conditions as possible
hostname: sumaform-test-ctl
product_version: head
install_salt_bundle: true
gpg_keys: ['testkey.pub']
domain: tf.local
use_avahi: 0
timezone: Europe/Berlin
use_ntp: true
ipv6: {'accept_ra': true, 'enable': true}
additional_repos: {'testrepo': 'http://example.com/testrepo'}
additional_certs: {'testcert': 'http://example.com/testcert'}
additional_packages: ['testpkg']
authorized_keys: [ssh-rsa 1233= root@travis.git]
reset_ids: true
use_os_released_updates: true
swap_file_size: 1024
mirror: mirror.tf.local
testsuite: true
minion: suse-minion-1.tf.local
minions: ['suse-minion-1.tf.local', 'suse-minion-2.tf.local']
EOF

cat > testconfig/minion <<EOF
root_dir: $PWD
id: sumaform-test-ctl
EOF

cat testconfig/grains
echo

rendered_bashrc="$PWD/testconfig/controller-bashrc"
salt-call cp.get_template salt://controller/bashrc "$rendered_bashrc" template=jinja --local --file-root=salt/ --config-dir=testconfig --retcode-passthrough || exit $?
grep -F 'export MINION="suse-minion-1.tf.local"' "$rendered_bashrc" || exit 1
inventory_line="$(grep '^export UYUNI_BENCH_MINIONS=' "$rendered_bashrc")" || exit 1
inventory_json="${inventory_line#export UYUNI_BENCH_MINIONS=\'}"
inventory_json="${inventory_json%\'}"
test "$(printf '%s\n' "$inventory_json" | jq -c .)" = '["suse-minion-1.tf.local","suse-minion-2.tf.local"]' || exit 1

salt-call state.show_highstate --local --file-root=salt/ --config-dir=testconfig --retcode-passthrough
