#! /bin/bash
set -x

mkdir -p testconfig

cat > testconfig/grains <<EOF
hostname: sumaform-test-client
gpg_keys: []
domain: tf.local
use_avahi: 0
timezone: Europe/Berlin
use_ntp: true
additional_repos: {}
additional_certs: {}
additional_packages: []
authorized_keys: [ssh-rsa 1233= root@sumaform.git]
reset_ids: true
product_version: head
server: sumaform-test-server.tf.local
roles: [client]
mirror: null
auto_register: false
testsuite: true
ipv6: {'accept_ra': true, 'enable': true}
install_salt_bundle: true
EOF

cat > testconfig/minion <<EOF
root_dir: $PWD
id: sumaform-test-client
EOF

cat testconfig/grains
echo

salt-call state.show_highstate --local --file-root=salt/ --config-dir=testconfig --retcode-passthrough
