ingressSslAnnotations:
  cert-manager.io/issuer: uyuni-ca-issuer
{%- if grains.get("container_repository") %}
repository: {{ grains.get("container_repository") }}
{%- endif %}
exposeJavaDebug: {{ grains.get("java_debugging") }}
uyuniMailFrom: notifications@{{ grains.get("fqdn") }}
fqdn: {{ grains.get("fqdn") }}
sccUser: {{ grains.get("cc_username") }}
sccPass: {{ grains.get("cc_password") }}
