#!/usr/bin/bash

help() {
    echo "$0 exec cmd-to-run --args"
}

KUBE_POD=$(kubectl get pod -lapp=uyuni -o jsonpath={.items[0].metadata.name})

case $1 in
  exec)
    shift
        if [ -z "$KUBE_POD" ]; then
            podman exec uyuni-server $@
        else
            kubectl exec $KUBE_POD -c uyuni -- $@
        fi
    ;;
  *)
    help
esac
