# This file comes from: https://github.com/uyuni-project/uyuni-charts/blob/main/README.md

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      reportdb-pgsql:
        port: 5432
        expose:
          default: true
        exposedPort: 5432
        protocol: TCP
        hostPort: 5432
        containerPort: 5432
      salt-publish:
        port: 4505
        expose:
          default: true
        exposedPort: 4505
        protocol: TCP
        hostPort: 4505
        containerPort: 4505
      salt-request:
        port: 4506
        expose:
          default: true
        exposedPort: 4506
        protocol: TCP
        hostPort: 4506
        containerPort: 4506
      # Only if java debugging is enabled
      tasko-debug:
        port: 8001
        expose:
          default: true
        exposedPort: 8001
        protocol: TCP
        hostPort: 8001
      search-debug:
        port: 8002
        expose:
          default: true
        exposedPort: 8002
        protocol: TCP
        hostPort: 8002
      tomcat-debug:
        port: 8003
        expose:
          default: true
        exposedPort: 8003
        protocol: TCP
        hostPort: 8003
