apiVersion: v1
kind: PersistentVolume
metadata:
  name: var-pgsql18
  annotations:
    pv.kubernetes.io/provisioned-by: rancher.io/local-path
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path

  claimRef:
    namespace: uyuni
    name: var-pgsql18
  hostPath:
    path: /opt/local-path-provisioner/var-pgsql18
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
