# Per-user open files limits
root           soft   nofile         32768
root           hard   nofile         32768

admin          soft   nofile         32768
admin          hard   nofile         32768
