{
 "title": "PostgreSQL database insights",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(up{role='postgres'} , instance)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_locks_count{instance=~\"$server:.*\", datname=~\"susemanager|suma\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Operations on tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_fetched{instance=~\"$server:.*\", datname=\"$db\"}[5m]))",
     "legendFormat": "fetches"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_inserted{instance=~\"$server:.*\", datname=\"$db\"}[5m]))",
     "legendFormat": "inserts"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_updated{instance=~\"$server:.*\", datname=\"$db\"}[5m]))",
     "legendFormat": "updates"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(pg_stat_database_tup_deleted{instance=~\"$server:.*\", datname=\"$db\"}[5m]))",
     "legendFormat": "deletes"
    }
   ]
  },
  { "title": "Locks and Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Locks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, datname, mode) (pg_locks_count{instance=~\"$server:.*\", datname=\"$db\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Commits vs rollbacks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, datname) (pg_stat_database_xact_commit{instance=~\"$server:.*\", datname=\"$db\"})",
     "legendFormat": "commits"
    },
    {
     "expr": "sum by (instance, datname) (pg_stat_database_xact_rollback{instance=~\"$server:.*\", datname=\"$db\"})",
     "legendFormat": "rollbacks"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, datname, state) (pg_stat_activity_count{instance=~\"$server:.*\", datname=\"$db\"})",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}