{
 "title": "SUSE Manager Server",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu{job=\"sumaform\",mode=\"user\"}[1m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu{job=\"sumaform\",mode=\"system\"}[1m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu{job=\"sumaform\",mode!~\"user|system|idle\"}[1m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "CPU Saturation (Runnable Processes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{job=\"sumaform\"}",
     "legendFormat": "running"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{job=\"sumaform\"} - node_memory_MemAvailable{job=\"sumaform\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Memory Saturation (Swap Utilization)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal{job=\"sumaform\"} - node_memory_SwapFree{job=\"sumaform\"}",
     "legendFormat": "swapped"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{job=\"sumaform\", device=\"eth0\"}[1m])",
     "legendFormat": "in"
    },
    {
     "expr": "irate(node_network_transmit_bytes{job=\"sumaform\", device=\"eth0\"}[1m])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Saturation (FIFO buffer errors)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_fifo{job=\"sumaform\",device=\"eth0\"}",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Storage I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Storage I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job=\"sumaform\", device=~\"sda|vda|xvda\"}[30s])/1000",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Storage I/O Saturation (I/O average queue length)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Average Length" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted{job=\"sumaform\",device=~\"sda|vda|xvda\"}[30s])/1000",
     "legendFormat": "length"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "PostgreSQL Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Locks" }
   ],
   "targets": [
    {
     "expr": "sum(pg_locks_count{job=\"sumaform\",datname=\"susemanager\", mode=~\".*exclusive.*\"})",
     "legendFormat": "exclusive"
    },
    {
     "expr": "sum(pg_locks_count{job=\"sumaform\",datname=\"susemanager\", mode!~\".*exclusive.*\"})",
     "legendFormat": "shared"
    }
   ]
  },
  {
   "title": "PostgreSQL Operations on Tuples",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{job=\"sumaform\", datname=\"susemanager\"}[30s])",
     "legendFormat": "fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{job=\"sumaform\", datname=\"susemanager\"}[30s])",
     "legendFormat": "inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_updated{job=\"sumaform\",datname=\"susemanager\"}[30s])",
     "legendFormat": "updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_deleted{job=\"sumaform\",datname=\"susemanager\"}[30s])",
     "legendFormat": "deleted"
    }
   ]
  },
  { "title": "Java", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Tomcat JVM Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{job=\"sumaform\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Tomcat JVM Heap Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"sumaform\"}",
     "legendFormat": "used"
    }
   ]
  },
  { "title": "Tomcat I", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "MessageQueue Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_threads_active{job=\"tomcat\"}",
     "legendFormat": "busy threads"
    },
    {
     "expr": "message_queue_thread_pool_threads{job=\"tomcat\"} - message_queue_thread_pool_threads_active{job=\"tomcat\"}",
     "legendFormat": "free threads"
    }
   ]
  },
  {
   "title": "MessageQueue Saturation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_task_count{job=\"tomcat\"} - message_queue_thread_pool_completed_task_count{job=\"tomcat\"}",
     "legendFormat": "queued tasks"
    }
   ]
  },
  { "title": "Tomcat II", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Tomcat Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Catalina_ThreadPool_currentThreadsBusy{name=\"\\\"ajp-apr-0:0:0:0:0:0:0:1-8009\\\"\"}",
     "legendFormat": "busy threads"
    },
    {
     "expr": "Catalina_ThreadPool_currentThreadCount{name=\"\\\"ajp-apr-0:0:0:0:0:0:0:1-8009\\\"\"} - Catalina_ThreadPool_currentThreadsBusy{name=\"\\\"ajp-apr-0:0:0:0:0:0:0:1-8009\\\"\"}",
     "legendFormat": "free threads"
    }
   ]
  },
  {
   "title": "MessageQueue Service Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(message_queue_thread_pool_completed_task_count{job=\"tomcat\"}[1m])",
     "legendFormat": "tasks per second"
    }
   ]
  },
  { "title": "Taskomatic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Taskomatic Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "taskomatic_scheduler_threads_active",
     "legendFormat": "busy threads"
    },
    {
     "expr": "taskomatic_scheduler_threads - taskomatic_scheduler_threads_active",
     "legendFormat": "free threads"
    }
   ]
  },
  {
   "title": "Taskomatic Service Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(taskomatic_scheduler_completed_task_count[1m])",
     "legendFormat": "tasks per second"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Action queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mgr_serveractions_queued{job=\"sumaform\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "mgr_serveractions_picked_up{job=\"sumaform\"}",
     "legendFormat": "picked up"
    }
   ]
  },
  {
   "title": "Action completion rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mgr_serveractions_completed{job=\"sumaform\"}[100s])",
     "legendFormat": "completed"
    },
    {
     "expr": "rate(mgr_serveractions_failed{job=\"sumaform\"}[30s])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Salt Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "salt_events_count{job=\"sumaform\"}"
    }
   ]
  },
  {
   "title": "Locust I",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simulated Users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "locust_user_count", "legendFormat": "users" }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(locust_requests_current_rps)",
       "legendFormat": "rps"
      }
     ]
    }
   ]
  },
  {
   "title": "Locust II",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avarage Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "locust_requests_avg_response_time",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "HTTP  Failures per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(locust_requests_num_failures[5m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}