name: PR event trigger

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  trigger:
    name: Publish the pull request number
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Save the pull request number
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: echo "PR_NUMBER=${PR_NUMBER}" > pr-metadata

    - name: Upload the pull request metadata
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v5.0.0
      with:
        name: pr-metadata
        path: pr-metadata
