#!/bin/bash
# combustion: network prepare
set -euxo pipefail

%{ if image == "leapmicro55o" }
function nm_config() {
  connectiondir="/etc/NetworkManager/system-connections"
  connectionfile="$connectiondir/Wired connection $1.nmconnection"
  mkdir -p "$connectiondir"
  cat > "$connectionfile" <<EOF
[connection]
id=Wired connection $1
type=ethernet
interface-name=$2

[ipv4]
method=auto

[ipv6]
addr-gen-mode=eui64
method=auto
EOF
  chmod go-r "$connectionfile"
}

# Name the Network Manager connections (preparation phase in initrd)
if [ "$${1-}" = "--prepare" ]; then
  nm_config 1 eth0
  nm_config 2 eth1
  exit 0
fi
%{ endif } # end of image == "leapmicro55o" block

# Redirect output to the console
exec > >(exec tee -a /var/log/combustion) 2>&1

%{ if image == "leapmicro55o" }
# Name the Network Manager connections (final phase on real filesystem)
nm_config 1 eth0
nm_config 2 eth1
%{ endif }


# Set linux as password for root
echo 'root:$6$3aQC9rrDLHiTf1yR$NoKe9tko0kFIpu0rQ2y/OzOOtbVvs0Amr2bx0T4cGf6aq8PG74EmVy8lSDJdbLVVFpOSzwELWyReRCiPHa7DG0' | chpasswd -e

# SL Micro6: Add PermitRootLogin to sshd config
%{ if image == "slmicro60o" }
echo "PermitRootLogin yes" > /etc/ssh/sshd_config.d/root.conf
echo "ChallengeResponseAuthentication yes" >> /etc/ssh/sshd_config.d/root.conf
%{ endif }

# Add a public ssh key and enable sshd
systemctl enable sshd.service

# Add the GPG keys
${ gpg_keys }

# Add repositories
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/SUSE:/CA/15.5/ ca_suse

%{ if image == "leapmicro55o" }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Master:/openSUSE_Leap_15-Uyuni-Client-Tools/openSUSE_Leap_15.0/ client_tools_repo

%{ if container_server || container_proxy }
%{ if product_version == "uyuni-master" || product_version == "uyuni-pr" }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Master:/ContainerUtils/openSUSE_Leap_Micro_5.5/ container_utils
%{ else }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Stable:/ContainerUtils/openSUSE_Leap_Micro_5.5/ container_utils
%{ endif }
%{ endif }

%{ if testsuite }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Test-Packages:/Pool/rpm/ test_repo_rpm_pool

# Leap repos are required to install expect
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/distribution/leap/15.5/repo/oss/ leap_pool_repo
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/update/leap/15.5/oss/ leap_update_repo
%{ endif }

%{ if container_runtime == "k3s" }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/update/leap/15.5/sle/ sle_update_repo
%{ endif }
%{ endif } # end of image == "leapmicro55o" block


%{ if image == "slemicro51-ign" }
%{ if testsuite }
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product os_pool_repo
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs" }/SUSE/Products/SUSE-MicroOS/5.1/x86_64/product/ micro_pool_repo
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs" }/SUSE/Updates/SUSE-MicroOS/5.1/x86_64/update/ micro_update_repo
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs" }/Devel:/Galaxy:/Manager:/Head:/SLE15-SUSE-Manager-Tools/images/repo/SLE-15-Manager-Tools-POOL-x86_64-Media1/ tools_pool_repo

%{ endif }
%{ endif }

%{ if image == "slemicro52-ign" }
%{ endif }

%{ if image == "slemicro53-ign" }
%{ endif }

%{ if image == "slemicro54-ign" }
%{ endif }

%{ if image == "slmicro60o" }
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SL-Micro/6.0/x86_64/product/ os_pool_repo

# SL Micro 6.0 is being used in both Uyuni and SUSE Manager
# we do not support yet Leap Micro 6.0, even in Uyuni
%{ if product_version == "uyuni-master" || product_version == "uyuni-released" || product_version == "uyuni-pr" }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Master:/SLMicro6-Uyuni-Client-Tools/SL-Micro6/ client_tools_repo
%{ else }
zypper ar http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SUSE-Manager-Tools-For-SL-Micro/6/x86_64/product/ tools_pool_repo
%{ endif }


%{ if testsuite }
zypper ar http://${ use_mirror_images ? mirror : "download.opensuse.org" }/repositories/systemsmanagement:/Uyuni:/Test-Packages:/Pool/rpm/ test_repo_rpm_pool
%{ endif }
%{ endif } # end of image == "slmicro60o" block

for i in ${additional_repos}; do
  name=$(echo $i | cut -d= -f1)
  url=$(echo $i | cut -d= -f2)
  %{ if product_version == "uyuni-pr" }
    zypper ar --no-gpgcheck $url $name
  %{ else }
    zypper ar $url $name
  %{ endif }
done

# Install packages
PACKAGES="qemu-guest-agent avahi ca-certificates"

%{ if container_runtime == "podman" }
PACKAGES="$PACKAGES podman netavark aardvark-dns"
%{ endif }

%{ if container_runtime == "k3s" }
PACKAGES="$PACKAGES helm"
%{ endif }

%{ if container_server || container_proxy }
PACKAGES="$PACKAGES bash-completion ca-certificates-suse"
%{ if testsuite }
PACKAGES="$PACKAGES expect bind-utils"
%{ endif }
%{ endif }

%{ if container_server }
PACKAGES="$PACKAGES mgradm mgrctl mgradm-bash-completion mgrctl-bash-completion"
%{ endif }

%{ if container_proxy }
PACKAGES="$PACKAGES  mgrpxy"
%{ endif }

%{ if install_salt_bundle }
PACKAGES="$PACKAGES venv-salt-minion"
%{ else }
PACKAGES="$PACKAGES salt-minion"
%{ endif }

%{ if testsuite }
PACKAGES="$PACKAGES andromeda-dummy milkyway-dummy virgo-dummy timezone wget aaa_base-extras"
%{ endif }

zypper --non-interactive install $PACKAGES

# Leave a marker
echo "Configured with combustion" > /etc/issue.d/combustion
