#cloud-config

disable_root: false
ssh_pwauth: true
chpasswd:
  expire: false
  list: |
     root:linux

%{ if image == "centos6o" }
bootcmd:
  # WORKAROUND: yum_repos state cant replace a repo, so we need to delete it,
  # otherwise the workaround for archived repo doesn't work
  - [rm, -f, /etc/yum.repos.d/CentOS-Base.repo]

yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS6-Uyuni-Client-Tools/CentOS_6/
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
    priority: 98
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/6/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
    failovermethod: priority
    enabled: true
    gpgcheck: false
    priority: 99
    name: epel
  # repo for Centos-Base backup
  CentOS-Base_backup:
    baseurl: http://vault.centos.org/centos/6/os/$basearch
    failovermethod: priority
    enabled: true
    gpgcheck: false
    priority: 99
    name: CentOS-Base_backup
  # repo for Centos-Updates backup
  CentOS-Updates_backup:
    baseurl: http://vault.centos.org/centos/6/updates/$basearch
    failovermethod: priority
    enabled: true
    gpgcheck: false
    priority: 99
    name: CentOS-Updates_backup

packages: ["salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  # WORKAROUND: CentOS 6 changes the root password with a random one after cloud-init. Disable the mechanism
  - "rm -f /root/firstrun"
  # WORKAROUND: cloud-init in CentOS 6 does not take care of the following
  - "sed -i -e's/without-password/yes/' /etc/ssh/sshd_config"
  - "service sshd restart"
  - "service qemu-ga start"
%{ endif }

%{ if image == "centos7o" }
yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS7-Uyuni-Client-Tools/CentOS_7/
    failovermethod: priority
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
    priority: 98
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/7/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    failovermethod: priority
    enabled: true
    gpgcheck: false
    priority: 99
    name: epel

packages: ["salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]
%{ endif }

%{ if image == "centos8o" }
yum_repos:
  # repo for salt
  tools_pool_repo:
    baseurl: http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/CentOS8-Uyuni-Client-Tools/CentOS_8/
    failovermethod: priority
    enabled: true
    gpgcheck: false
    name: tools_pool_repo
    priority: 98
  # repo for nss-mdns
  epel:
    baseurl: http://download.fedoraproject.org/pub/epel/8/$basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-8&arch=$basearch
    failovermethod: priority
    enabled: true
    gpgcheck: false
    priority: 99
    name: epel

packages: ["salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]
%{ endif }

%{ if image == "opensuse150o" }
packages: ["salt-minion", "avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  - zypper removerepo --all
%{ endif }

%{ if image == "opensuse151o" }
packages: ["qemu-guest-agent"]

runcmd:
  - zypper removerepo --all
%{ endif }

%{ if image == "opensuse152o" }
packages: ["qemu-guest-agent"]

runcmd:
  - zypper removerepo --all
%{ endif }

%{ if image == "sles12sp4o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-SERVER/12-SP4/x86_64/product/
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]
%{ endif }

%{ if image == "sles12sp5o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-SERVER/12-SP5/x86_64/product/
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]
%{ endif }

%{ if image == "sles15o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Basesystem/15/x86_64/product
      enabled: 1
      autorefresh: 1
      ## WORKAROUND: name of server app repo needs to be alphabetically after the base system repo to force GPG key update
    - id: server_applications_pool_repo
      name: module_server_applications_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Server-Applications/15/x86_64/product
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  # WORKAROUND: cloud-init in SLES 15 does not take care of the following
  - "systemctl start 'qemu-ga@virtio\\x2dports-org.qemu.guest_agent.0'"
%{ endif }

%{ if image == "sles15sp1o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product
      enabled: 1
      autorefresh: 1
    - id: module_server_applications_pool_repo
      name: module_server_applications_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Server-Applications/15-SP1/x86_64/product
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  # WORKAROUND: cloud-init in SLES 15 SP1 does not take care of the following
  - "systemctl start 'qemu-ga@virtio\\x2dports-org.qemu.guest_agent.0'"
%{ endif }

%{ if image == "sles15sp2o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Basesystem/15-SP2/x86_64/product
      enabled: 1
      autorefresh: 1
    - id: module_server_applications_pool_repo
      name: module_server_applications_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Server-Applications/15-SP2/x86_64/product
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  # WORKAROUND: cloud-init in SLES 15 SP2 does not take care of the following
  - "systemctl start 'qemu-ga@virtio\\x2dports-org.qemu.guest_agent.0'"
%{ endif }

%{ if image == "sles15sp3o" }
zypper:
  repos:
    - id: os_pool_repo
      name: os_pool_repo
      baseurl: http://${ use_mirror_images ? mirror : "download.suse.de/ibs"}/SUSE/Products/SLE-Module-Basesystem/15-SP3/x86_64/product
      enabled: 1
      autorefresh: 1

packages: ["avahi", "nss-mdns", "qemu-guest-agent"]

runcmd:
  # WORKAROUND: cloud-init in SLES 15 SP3 does not take care of the following
  - "systemctl start 'qemu-ga@virtio\\x2dports-org.qemu.guest_agent.0'"
%{ endif }

%{ if image == "ubuntu1604o" }
apt:
  conf: |
    APT {
      Get {
        "AllowUnauthenticated" true;
      };
    };
  sources:
    tools_pool_repo:
      source: deb http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu1604-Uyuni-Client-Tools/xUbuntu_16.04 /
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1.4.5 (GNU/Linux)

        mQENBFsnulUBCADNjL4hvhVtSzqVDlMtFFFP28Acq+UNF8WKKMhbBirfOpXwwI1C
        NR3i0CXPOce5eKShuuWAjD2E36e2XAp3rUAo/aCA7UgtJkMNKzzlTOcqHHxKTx6H
        gvp0Fb6xTKywZ7VttGhwUynl+CsDuOst3ROXTNdb8XMfm4joH2FW5D3ACN2qNiv0
        MVcFNKxQ98w8M9xJxdI8DuyngnSeZwAosNzEio3JhTPiTv9ngY2Z3AuYUcwTEt7o
        feEN+ivAgYnn+a6DBKFBeCW7VUD3V+tH8/fKnkvI4gf2o3N7Ok+/uE+DPUBb+14f
        +9dhBjd+7+pR3ayEZFjQns5XFShoYu2+CQspABEBAAG0UHN5c3RlbXNtYW5hZ2Vt
        ZW50OlV5dW5pIE9CUyBQcm9qZWN0IDxzeXN0ZW1zbWFuYWdlbWVudDpVeXVuaUBi
        dWlsZC5vcGVuc3VzZS5vcmc+iQE+BBMBCAAoBQJfM/XhAhsDBQkIKuuMBgsJCAcD
        AgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCXLl1sDSCDPqQnB/wMkQdu3FtPd+Jppc9G
        TLbSZC2CDLfGpciuBYU4yiUY6F8Gt2KASRQe9lHiKtJKeKpRXsXu1tEUuTr8xp2R
        PbP+TKT2u7HFIEfrQUl5poSXSrEqtQyzaciTYxV343EWr+kn3Ry4M3Cj1uiMOYGd
        UIT61uye1TUxbvnGLbl6NUl+KOgtH3DQZf6xLr+yCD/y97FHpLCGQtMMwQdcJ25z
        9fmJlBb8SEOe0blfOQP2RTZe6pIuLvR+rbA+fj5fGI9m5VV1gznVXjY6PFlEwW9k
        UaJlMJ4ximis8qO/8SMLI5y9AQC8gSy4qKc6oYe3TEnaK/GjRrEXNbKBkEKw3z0m
        tbC0iEYEExECAAYFAlsnulUACgkQOzARt2udZSO/4QCcDf+j/XRbJn2PudsSoyjw
        3B2boakAnA9A9b8UoEYgmLTRpwXYuhsxOCDE
        =H9dm
        -----END PGP PUBLIC KEY BLOCK-----

runcmd:
  # WORKAROUND: cloud-init in Ubuntu 16.04 does not take care of the following
  - "sed -i -e's/prohibit-password/yes/' /etc/ssh/sshd_config"
  - systemctl restart sshd

packages: ["salt-minion", "avahi-daemon", "qemu-guest-agent"]
%{ endif }

%{ if image == "ubuntu1804o" }

runcmd:
  # WORKAROUND: cloud-init in Ubuntu 18.04 does not take care of the following
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd

packages: ["salt-minion", "avahi-daemon", "qemu-guest-agent"]
%{ endif }

%{ if image == "ubuntu2004o" }

apt:
  sources:
    tools_pool_repo:
      source: deb http://${ use_mirror_images ? mirror : "download.opensuse.org"}/repositories/systemsmanagement:/Uyuni:/Stable:/Ubuntu2004-Uyuni-Client-Tools/xUbuntu_20.04/ /
      key: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----
        Version: GnuPG v1.4.5 (GNU/Linux)

        mQENBFsnulUBCADNjL4hvhVtSzqVDlMtFFFP28Acq+UNF8WKKMhbBirfOpXwwI1C
        NR3i0CXPOce5eKShuuWAjD2E36e2XAp3rUAo/aCA7UgtJkMNKzzlTOcqHHxKTx6H
        gvp0Fb6xTKywZ7VttGhwUynl+CsDuOst3ROXTNdb8XMfm4joH2FW5D3ACN2qNiv0
        MVcFNKxQ98w8M9xJxdI8DuyngnSeZwAosNzEio3JhTPiTv9ngY2Z3AuYUcwTEt7o
        feEN+ivAgYnn+a6DBKFBeCW7VUD3V+tH8/fKnkvI4gf2o3N7Ok+/uE+DPUBb+14f
        +9dhBjd+7+pR3ayEZFjQns5XFShoYu2+CQspABEBAAG0UHN5c3RlbXNtYW5hZ2Vt
        ZW50OlV5dW5pIE9CUyBQcm9qZWN0IDxzeXN0ZW1zbWFuYWdlbWVudDpVeXVuaUBi
        dWlsZC5vcGVuc3VzZS5vcmc+iQE+BBMBCAAoBQJfM/XhAhsDBQkIKuuMBgsJCAcD
        AgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCXLl1sDSCDPqQnB/wMkQdu3FtPd+Jppc9G
        TLbSZC2CDLfGpciuBYU4yiUY6F8Gt2KASRQe9lHiKtJKeKpRXsXu1tEUuTr8xp2R
        PbP+TKT2u7HFIEfrQUl5poSXSrEqtQyzaciTYxV343EWr+kn3Ry4M3Cj1uiMOYGd
        UIT61uye1TUxbvnGLbl6NUl+KOgtH3DQZf6xLr+yCD/y97FHpLCGQtMMwQdcJ25z
        9fmJlBb8SEOe0blfOQP2RTZe6pIuLvR+rbA+fj5fGI9m5VV1gznVXjY6PFlEwW9k
        UaJlMJ4ximis8qO/8SMLI5y9AQC8gSy4qKc6oYe3TEnaK/GjRrEXNbKBkEKw3z0m
        tbC0iEYEExECAAYFAlsnulUACgkQOzARt2udZSO/4QCcDf+j/XRbJn2PudsSoyjw
        3B2boakAnA9A9b8UoEYgmLTRpwXYuhsxOCDE
        =H9dm
        -----END PGP PUBLIC KEY BLOCK-----

runcmd:
  # WORKAROUND: cloud-init in Ubuntu 20.04 does not take care of the following
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - systemctl start qemu-guest-agent

packages: ["salt-minion", "avahi-daemon", "qemu-guest-agent"]
%{ endif }
%{ if image == "debian10o" }
runcmd:
#   HACK: cloud-init in Debian 10 does not take care of the following
  - echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
  - systemctl restart sshd
  - systemctl start qemu-guest-agent

packages: ["salt-minion", "avahi-daemon", "qemu-guest-agent", "apt-transport-https", "python-apt", "python3-apt"]
%{ endif }
%{ if image == "debian9o" }
runcmd:
#   HACK: cloud-init in Debian 9 does not take care of the following
  - echo '\nPermitRootLogin yes' >> /etc/ssh/sshd_config
  - systemctl restart sshd

packages: ["salt-minion", "avahi-daemon", "qemu-guest-agent", "apt-transport-https", "python-apt", "python3-apt"]
%{ endif }
